# Generated by Django 4.0.2 on 2022-06-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postview_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postview',
            old_name='time',
            new_name='time_stamp',
        ),
    ]
